export const data = JSON.parse("{\"key\":\"v-4808ad6a\",\"path\":\"/study/frontend/react/ReactCli.html\",\"title\":\"ReactCli\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"react\",\"date\":\"2022-05-24T00:00:00.000Z\",\"article\":true,\"category\":[\"React\"],\"tag\":[\"ReactCli\"],\"summary\":\"ReactCli 一、todoList案例相关知识点 1.拆分组件、实现静态组件，注意：className、style的写法 2.动态初始化列表，如何确定将数据放在哪个组件的state中？ ——某个组件使用：放在其自身的state中 ——某些组件使用：放在他们共同的父组件state中（官方称此操作为：状态提升） 3.关于父子之间通信： 1.【父组件】给【子组\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://doc.shaoclean.top/study/frontend/react/ReactCli.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"clog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ReactCli\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"ReactCli\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-05-24T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"一、todoList案例相关知识点\",\"slug\":\"一、todolist案例相关知识点\",\"link\":\"#一、todolist案例相关知识点\",\"children\":[]},{\"level\":2,\"title\":\"二、github搜索案例相关知识点\",\"slug\":\"二、github搜索案例相关知识点\",\"link\":\"#二、github搜索案例相关知识点\",\"children\":[]},{\"level\":2,\"title\":\"三、路由的基本使用\",\"slug\":\"三、路由的基本使用\",\"link\":\"#三、路由的基本使用\",\"children\":[]},{\"level\":2,\"title\":\"四、路由组件与一般组件\",\"slug\":\"四、路由组件与一般组件\",\"link\":\"#四、路由组件与一般组件\",\"children\":[]},{\"level\":2,\"title\":\"五、NavLink与封装NavLink\",\"slug\":\"五、navlink与封装navlink\",\"link\":\"#五、navlink与封装navlink\",\"children\":[]},{\"level\":2,\"title\":\"六、Switch的使用\",\"slug\":\"六、switch的使用\",\"link\":\"#六、switch的使用\",\"children\":[]},{\"level\":2,\"title\":\"七、解决多级路径刷新页面样式丢失的问题\",\"slug\":\"七、解决多级路径刷新页面样式丢失的问题\",\"link\":\"#七、解决多级路径刷新页面样式丢失的问题\",\"children\":[]},{\"level\":2,\"title\":\"八、路由的严格匹配与模糊匹配\",\"slug\":\"八、路由的严格匹配与模糊匹配\",\"link\":\"#八、路由的严格匹配与模糊匹配\",\"children\":[]},{\"level\":2,\"title\":\"九、Redirect的使用\",\"slug\":\"九、redirect的使用\",\"link\":\"#九、redirect的使用\",\"children\":[]},{\"level\":2,\"title\":\"十、嵌套路由\",\"slug\":\"十、嵌套路由\",\"link\":\"#十、嵌套路由\",\"children\":[]},{\"level\":2,\"title\":\"十一、向路由组件传递参数\",\"slug\":\"十一、向路由组件传递参数\",\"link\":\"#十一、向路由组件传递参数\",\"children\":[]},{\"level\":2,\"title\":\"十二、编程式路由导航\",\"slug\":\"十二、编程式路由导航\",\"link\":\"#十二、编程式路由导航\",\"children\":[]},{\"level\":2,\"title\":\"十三、BrowserRouter与HashRouter的区别\",\"slug\":\"十三、browserrouter与hashrouter的区别\",\"link\":\"#十三、browserrouter与hashrouter的区别\",\"children\":[]},{\"level\":2,\"title\":\"十四、antd的按需引入+自定主题\",\"slug\":\"十四、antd的按需引入-自定主题\",\"link\":\"#十四、antd的按需引入-自定主题\",\"children\":[]}],\"readingTime\":{\"minutes\":4.77,\"words\":1431},\"filePathRelative\":\"study/frontend/react/ReactCli.md\",\"localizedDate\":\"2022年5月24日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
