export const data = JSON.parse("{\"key\":\"v-88be0674\",\"path\":\"/study/frontend/vue/Vue2.html\",\"title\":\"Vue2\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"vue\",\"date\":\"2022-02-09T00:00:00.000Z\",\"start\":11,\"category\":[\"前端\",\"Vue\"],\"tag\":[\"Vue2\"],\"summary\":\"Vue2 vue.config.js配置文件 \\\"使用vue inspect > output.js可以查看到Vue脚手架的默认配置\\\" \\\"使用vue.config.js可以对脚手架进行个性化定制，详情见:https://cli:vue.js.org/zh\\\" ref属性 配置项props 功能：让组件接受外部传过来的数据 （1）传递数据： (2)接收数据 第一种\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://doc.shaoclean.top/study/frontend/vue/Vue2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"clog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Vue2\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue2\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-02-09T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"vue.config.js配置文件\",\"slug\":\"vue-config-js配置文件\",\"link\":\"#vue-config-js配置文件\",\"children\":[]},{\"level\":2,\"title\":\"ref属性\",\"slug\":\"ref属性\",\"link\":\"#ref属性\",\"children\":[]},{\"level\":2,\"title\":\"配置项props\",\"slug\":\"配置项props\",\"link\":\"#配置项props\",\"children\":[]},{\"level\":2,\"title\":\"mixin(混入)\",\"slug\":\"mixin-混入\",\"link\":\"#mixin-混入\",\"children\":[]},{\"level\":2,\"title\":\"插件\",\"slug\":\"插件\",\"link\":\"#插件\",\"children\":[]},{\"level\":2,\"title\":\"总结ToDoList案例\",\"slug\":\"总结todolist案例\",\"link\":\"#总结todolist案例\",\"children\":[]},{\"level\":2,\"title\":\"webStorage\",\"slug\":\"webstorage\",\"link\":\"#webstorage\",\"children\":[]},{\"level\":2,\"title\":\"组件的自定义事件\",\"slug\":\"组件的自定义事件\",\"link\":\"#组件的自定义事件\",\"children\":[]},{\"level\":2,\"title\":\"全局事件总线（GlobalEventBus）\",\"slug\":\"全局事件总线-globaleventbus\",\"link\":\"#全局事件总线-globaleventbus\",\"children\":[]},{\"level\":2,\"title\":\"消息订阅与发布\",\"slug\":\"消息订阅与发布\",\"link\":\"#消息订阅与发布\",\"children\":[]},{\"level\":2,\"title\":\"nextTick\",\"slug\":\"nexttick\",\"link\":\"#nexttick\",\"children\":[]},{\"level\":2,\"title\":\"Vue封装的过渡与动画\",\"slug\":\"vue封装的过渡与动画\",\"link\":\"#vue封装的过渡与动画\",\"children\":[]},{\"level\":2,\"title\":\"Vue脚手架配置代理\",\"slug\":\"vue脚手架配置代理\",\"link\":\"#vue脚手架配置代理\",\"children\":[]},{\"level\":2,\"title\":\"插槽\",\"slug\":\"插槽\",\"link\":\"#插槽\",\"children\":[]},{\"level\":2,\"title\":\"Vuex\",\"slug\":\"vuex\",\"link\":\"#vuex\",\"children\":[]},{\"level\":2,\"title\":\"路由\",\"slug\":\"路由\",\"link\":\"#路由\",\"children\":[]}],\"readingTime\":{\"minutes\":18.68,\"words\":5604},\"filePathRelative\":\"study/frontend/vue/Vue2.md\",\"localizedDate\":\"2022年2月9日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
