export const data = JSON.parse("{\"key\":\"v-7bf12e24\",\"path\":\"/project/cyou-js.html\",\"title\":\"cyou-js\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"javascript\",\"date\":\"2022-08-13T00:00:00.000Z\",\"star\":9,\"category\":[\"前端\",\"使用文档\"],\"tag\":[\"cyou-js\"],\"summary\":\"cyou-js 使用 1.引入文件 2.初始化ctool 注意 由于Vue项目解析模板渲染页面机制的特殊性，使用起来可能会有点奇怪 当然这一点我们还在努力的改进中💪 在原生JS项目中，需要这样使用：; 1.首先需要创建一个``（该容器用于放置ctool，可以在此区域内自由的移动ctool） 2.在js中初始化cyou 在Vue项目中，则需要这样使用：; 恭\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://doc.shaoclean.top/project/cyou-js.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"clog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"cyou-js\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"cyou-js\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-08-13T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"使用\",\"slug\":\"使用\",\"link\":\"#使用\",\"children\":[{\"level\":3,\"title\":\"1.引入文件\",\"slug\":\"_1-引入文件\",\"link\":\"#_1-引入文件\",\"children\":[]},{\"level\":3,\"title\":\"2.初始化ctool\",\"slug\":\"_2-初始化ctool\",\"link\":\"#_2-初始化ctool\",\"children\":[]},{\"level\":3,\"title\":\"3.自定义根元素\",\"slug\":\"_3-自定义根元素\",\"link\":\"#_3-自定义根元素\",\"children\":[]},{\"level\":3,\"title\":\"4.添加根元素\",\"slug\":\"_4-添加根元素\",\"link\":\"#_4-添加根元素\",\"children\":[]},{\"level\":3,\"title\":\"5.使用功能\",\"slug\":\"_5-使用功能\",\"link\":\"#_5-使用功能\",\"children\":[]}]},{\"level\":2,\"title\":\"内置API\",\"slug\":\"内置api\",\"link\":\"#内置api\",\"children\":[{\"level\":3,\"title\":\"1.自由拖拽元素(ch)\",\"slug\":\"_1-自由拖拽元素-ch\",\"link\":\"#_1-自由拖拽元素-ch\",\"children\":[]},{\"level\":3,\"title\":\"2.创建元素(cr)\",\"slug\":\"_2-创建元素-cr\",\"link\":\"#_2-创建元素-cr\",\"children\":[]},{\"level\":3,\"title\":\"3.替换元素(re)\",\"slug\":\"_3-替换元素-re\",\"link\":\"#_3-替换元素-re\",\"children\":[]},{\"level\":3,\"title\":\"4.交换元素(ex)\",\"slug\":\"_4-交换元素-ex\",\"link\":\"#_4-交换元素-ex\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.08,\"words\":1223},\"filePathRelative\":\"project/cyou-js.md\",\"localizedDate\":\"2022年8月13日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
