export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"主页","icon":"home","type":"home","readingTime":{"minutes":0.55,"words":165},"excerpt":""},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"title":"幻灯片页","icon":"slides","type":"slide","readingTime":{"minutes":4.51,"words":1352},"excerpt":""},["/slides","/slides.md"]],
  ["v-c9bbfba2","/project/",{"title":"my-project！!","type":"article","readingTime":{"minutes":0.03,"words":10},"excerpt":""},["/project/index.html","/project/README.md"]],
  ["v-95b0645c","/project/project1.html",{"title":"cyou-js","type":"article","readingTime":{"minutes":0.01,"words":3},"excerpt":""},["/project/project1","/project/project1.md"]],
  ["v-9246b31e","/project/project2.html",{"title":"CYou","type":"article","readingTime":{"minutes":0.02,"words":5},"excerpt":""},["/project/project2","/project/project2.md"]],
  ["v-7c80db8b","/essay/",{"title":"Clean的随笔！!","type":"article","readingTime":{"minutes":0.04,"words":12},"excerpt":""},["/essay/index.html","/essay/README.md"]],
  ["v-19d508e8","/essay/feeling.html",{"title":"wuwuwu","icon":"edit","type":"article","readingTime":{"minutes":0.47,"words":141},"excerpt":"","date":"2022-01-06T00:00:00.000Z","localizedDate":"2022年1月6日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"],"star":10},["/essay/feeling","/essay/feeling.md"]],
  ["v-2468c9b8","/essay/feeling2.html",{"title":"feeling2","type":"article","readingTime":{"minutes":0.01,"words":2},"excerpt":""},["/essay/feeling2","/essay/feeling2.md"]],
  ["v-d7e37f4e","/study/frontend/js/ES6.html",{"title":"ES6","icon":"javascript","type":"article","readingTime":{"minutes":17.55,"words":5264},"excerpt":"","date":"2022-03-18T00:00:00.000Z","localizedDate":"2022年3月18日","category":["前端","JS"],"tag":["ES6"],"star":10},["/study/frontend/js/ES6","/study/frontend/js/ES6.md"]],
  ["v-30cd7070","/study/frontend/js/",{"title":"JS笔记","type":"page","readingTime":{"minutes":0.04,"words":13},"excerpt":""},["/study/frontend/js/index.html","/study/frontend/js/README.md"]],
  ["v-0cecb7e2","/study/frontend/angular/Angular.html",{"title":"Angular","type":"article","readingTime":{"minutes":19.59,"words":5877},"excerpt":"","category":["Angular"],"tag":["AngularCli"]},["/study/frontend/angular/Angular","/study/frontend/angular/Angular.md"]],
  ["v-242d4c0b","/study/frontend/angular/",{"title":"Angular笔记","type":"page","readingTime":{"minutes":0.04,"words":13},"excerpt":""},["/study/frontend/angular/index.html","/study/frontend/angular/README.md"]],
  ["v-7361fb8e","/study/frontend/react/",{"title":"React笔记","type":"page","readingTime":{"minutes":0.04,"words":13},"excerpt":""},["/study/frontend/react/index.html","/study/frontend/react/README.md"]],
  ["v-4808ad6a","/study/frontend/react/ReactCli.html",{"title":"ReactCli","icon":"react","type":"article","readingTime":{"minutes":4.77,"words":1431},"excerpt":"","date":"2022-05-24T00:00:00.000Z","localizedDate":"2022年5月24日","category":["React"],"tag":["ReactCli"],"star":10},["/study/frontend/react/ReactCli","/study/frontend/react/ReactCli.md"]],
  ["v-1b9f0d11","/study/frontend/react/ReactExtends.html",{"title":"React拓展","icon":"react","type":"article","readingTime":{"minutes":5.45,"words":1635},"excerpt":"","date":"2022-06-24T00:00:00.000Z","localizedDate":"2022年6月24日","category":["React"],"tag":["ReactExtends"],"star":8},["/study/frontend/react/ReactExtends","/study/frontend/react/ReactExtends.md"]],
  ["v-0b9533e7","/study/frontend/vue/",{"title":"vue笔记","type":"page","readingTime":{"minutes":0.04,"words":13},"excerpt":""},["/study/frontend/vue/index.html","/study/frontend/vue/README.md"]],
  ["v-88be0674","/study/frontend/vue/Vue2.html",{"title":"Vue2","icon":"vue","type":"article","readingTime":{"minutes":18.79,"words":5637},"excerpt":"这里是一些关于Vue2的笔记","date":"2022-02-09T00:00:00.000Z","localizedDate":"2022年2月9日","category":["前端","Vue"],"tag":["Vue2"],"star":11},["/study/frontend/vue/Vue2","/study/frontend/vue/Vue2.md"]],
  ["v-85545536","/study/frontend/vue/Vue3.html",{"title":"Vue3","type":"article","readingTime":{"minutes":0.06,"words":18},"excerpt":"","category":["Vue"],"tag":["Vue3"]},["/study/frontend/vue/Vue3","/study/frontend/vue/Vue3.md"]],
  ["v-0a824a52","/study/frontend/vue/article6.html",{"title":"文章 6","icon":"edit","type":"article","readingTime":{"minutes":0.12,"words":37},"excerpt":"","date":"2022-01-06T00:00:00.000Z","localizedDate":"2022年1月6日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"],"star":10},["/study/frontend/vue/article6","/study/frontend/vue/article6.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-3e5b7b84","/category/categorya/",{"title":"CategoryA 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categorya/index.html"]],
  ["v-06bbb262","/tag/tag-a/",{"title":"tag A 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-a/index.html"]],
  ["v-3e5b7ba3","/category/categoryb/",{"title":"CategoryB 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categoryb/index.html"]],
  ["v-06bbb224","/tag/tag-b/",{"title":"tag B 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-b/index.html"]],
  ["v-e9c7e408","/category/%E5%89%8D%E7%AB%AF/",{"title":"前端 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/前端/","/category/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-b3126996","/tag/es6/",{"title":"ES6 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/es6/index.html"]],
  ["v-3d184cee","/category/js/",{"title":"JS 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/js/index.html"]],
  ["v-05c2d0e3","/tag/angularcli/",{"title":"AngularCli 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/angularcli/index.html"]],
  ["v-2f218ea5","/category/angular/",{"title":"Angular 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/angular/index.html"]],
  ["v-5eb94b00","/tag/reactcli/",{"title":"ReactCli 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/reactcli/index.html"]],
  ["v-884bc6b0","/category/react/",{"title":"React 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/react/index.html"]],
  ["v-22f105a7","/tag/reactextends/",{"title":"ReactExtends 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/reactextends/index.html"]],
  ["v-65f6d381","/category/vue/",{"title":"Vue 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vue/index.html"]],
  ["v-2953c4b5","/tag/vue2/",{"title":"Vue2 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vue2/index.html"]],
  ["v-2953c4d4","/tag/vue3/",{"title":"Vue3 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vue3/index.html"]],
]
