export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"主页","icon":"home","type":"home","readingTime":{"minutes":0.55,"words":165},"excerpt":""},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"title":"幻灯片页","icon":"slides","type":"slide","readingTime":{"minutes":4.51,"words":1352},"excerpt":""},["/slides","/slides.md"]],
  ["v-097f202e","/project/CYOU.html",{"title":"CYou","icon":"javascript","type":"article","readingTime":{"minutes":1.71,"words":514},"excerpt":"","date":"2022-07-18T00:00:00.000Z","localizedDate":"2022年7月18日","category":["前端","项目文档"],"tag":["CYou"],"star":9},["/project/CYOU","/project/CYOU.md"]],
  ["v-c9bbfba2","/project/",{"title":"项目文档","type":"page","readingTime":{"minutes":0.19,"words":58},"excerpt":""},["/project/index.html","/project/README.md"]],
  ["v-7bf12e24","/project/cyou-js.html",{"title":"cyou-js","icon":"javascript","type":"article","readingTime":{"minutes":4.08,"words":1223},"excerpt":"","date":"2022-08-13T00:00:00.000Z","localizedDate":"2022年8月13日","category":["前端","使用文档"],"tag":["cyou-js"],"star":9},["/project/cyou-js","/project/cyou-js.md"]],
  ["v-7c80db8b","/essay/",{"title":"Clean的随笔","icon":"vue","type":"page","readingTime":{"minutes":0.05,"words":16},"excerpt":""},["/essay/index.html","/essay/README.md"]],
  ["v-120e4cc8","/essay/2022/7.html",{"title":"个人博客开通咯","icon":"edit","type":"article","readingTime":{"minutes":0.08,"words":23},"excerpt":"","date":"2022-09-07T00:00:00.000Z","localizedDate":"2022年9月7日","category":["随笔"],"tag":["tag A"],"star":10},["/essay/2022/7","/essay/2022/7.md"]],
  ["v-530c5edd","/essay/2022/feeling2.html",{"title":"feeling2","type":"article","readingTime":{"minutes":0.01,"words":2},"excerpt":""},["/essay/2022/feeling2","/essay/2022/feeling2.md"]],
  ["v-5325d9b2","/study/backend/java/JavaSE.html",{"title":"JavaSE","icon":"java","type":"article","readingTime":{"minutes":23.13,"words":6938},"excerpt":"","category":["后端","Java"],"tag":["JavaSE"],"star":8},["/study/backend/java/JavaSE","/study/backend/java/JavaSE.md"]],
  ["v-f451949a","/study/backend/java/",{"title":"Java笔记","icon":"java","type":"page","readingTime":{"minutes":0.05,"words":15},"excerpt":""},["/study/backend/java/index.html","/study/backend/java/README.md"]],
  ["v-0cecb7e2","/study/frontend/angular/Angular.html",{"title":"Angular","icon":"angular","type":"article","readingTime":{"minutes":19.62,"words":5887},"excerpt":"","category":["前端","Angular"],"tag":["AngularCli","学习笔记"],"star":5},["/study/frontend/angular/Angular","/study/frontend/angular/Angular.md"]],
  ["v-242d4c0b","/study/frontend/angular/",{"title":"Angular笔记","icon":"angular","type":"page","readingTime":{"minutes":0.05,"words":15},"excerpt":""},["/study/frontend/angular/index.html","/study/frontend/angular/README.md"]],
  ["v-d7e37f4e","/study/frontend/js/ES6.html",{"title":"ES6","icon":"javascript","type":"article","readingTime":{"minutes":17.59,"words":5276},"excerpt":"","date":"2022-03-18T00:00:00.000Z","localizedDate":"2022年3月18日","category":["前端","JS"],"tag":["ES6","学习笔记"],"star":10},["/study/frontend/js/ES6","/study/frontend/js/ES6.md"]],
  ["v-30cd7070","/study/frontend/js/",{"title":"JS笔记","icon":"javascript","type":"page","readingTime":{"minutes":0.05,"words":15},"excerpt":""},["/study/frontend/js/index.html","/study/frontend/js/README.md"]],
  ["v-7361fb8e","/study/frontend/react/",{"title":"React笔记","icon":"react","type":"page","readingTime":{"minutes":0.05,"words":15},"excerpt":""},["/study/frontend/react/index.html","/study/frontend/react/README.md"]],
  ["v-4808ad6a","/study/frontend/react/ReactCli.html",{"title":"ReactCli","icon":"react","type":"article","readingTime":{"minutes":4.79,"words":1437},"excerpt":"","date":"2022-05-24T00:00:00.000Z","localizedDate":"2022年5月24日","category":["前端","React"],"tag":["ReactCli","学习笔记"],"star":10},["/study/frontend/react/ReactCli","/study/frontend/react/ReactCli.md"]],
  ["v-1b9f0d11","/study/frontend/react/ReactExtends.html",{"title":"React拓展","icon":"react","type":"article","readingTime":{"minutes":5.47,"words":1641},"excerpt":"","date":"2022-06-24T00:00:00.000Z","localizedDate":"2022年6月24日","category":["前端","React"],"tag":["ReactExtends","学习笔记"],"star":8},["/study/frontend/react/ReactExtends","/study/frontend/react/ReactExtends.md"]],
  ["v-0b9533e7","/study/frontend/vue/",{"title":"vue笔记","icon":"vue","type":"page","readingTime":{"minutes":0.06,"words":19},"excerpt":""},["/study/frontend/vue/index.html","/study/frontend/vue/README.md"]],
  ["v-88be0674","/study/frontend/vue/Vue2.html",{"title":"Vue2","icon":"vue","type":"article","readingTime":{"minutes":18.8,"words":5641},"excerpt":"这里是一些关于Vue2的笔记","date":"2022-02-09T00:00:00.000Z","localizedDate":"2022年2月9日","category":["前端","Vue"],"tag":["Vue2","学习笔记"],"star":20},["/study/frontend/vue/Vue2","/study/frontend/vue/Vue2.md"]],
  ["v-85545536","/study/frontend/vue/Vue3.html",{"title":"Vue3","icon":"vue","type":"article","readingTime":{"minutes":0.09,"words":26},"excerpt":"","category":["前端","Vue"],"tag":["Vue3","学习笔记"]},["/study/frontend/vue/Vue3","/study/frontend/vue/Vue3.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-e9c7e408","/category/%E5%89%8D%E7%AB%AF/",{"title":"前端 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/前端/","/category/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-284a0545","/tag/cyou/",{"title":"CYou 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/cyou/index.html"]],
  ["v-778d8be5","/category/%E9%A1%B9%E7%9B%AE%E6%96%87%E6%A1%A3/",{"title":"项目文档 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/项目文档/","/category/%E9%A1%B9%E7%9B%AE%E6%96%87%E6%A1%A3/index.html"]],
  ["v-7ddbebe3","/tag/cyou-js/",{"title":"cyou-js 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/cyou-js/index.html"]],
  ["v-55de9cda","/category/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/",{"title":"使用文档 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/使用文档/","/category/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/index.html"]],
  ["v-06bbb262","/tag/tag-a/",{"title":"tag A 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-a/index.html"]],
  ["v-60649a06","/category/%E9%9A%8F%E7%AC%94/",{"title":"随笔 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/随笔/","/category/%E9%9A%8F%E7%AC%94/index.html"]],
  ["v-f0e09ea6","/tag/javase/",{"title":"JavaSE 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/javase/index.html"]],
  ["v-eddfd732","/category/%E5%90%8E%E7%AB%AF/",{"title":"后端 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/后端/","/category/%E5%90%8E%E7%AB%AF/index.html"]],
  ["v-05c2d0e3","/tag/angularcli/",{"title":"AngularCli 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/angularcli/index.html"]],
  ["v-5831b135","/category/java/",{"title":"Java 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/java/index.html"]],
  ["v-2ba7b1aa","/tag/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/",{"title":"学习笔记 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/学习笔记/","/tag/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/index.html"]],
  ["v-2f218ea5","/category/angular/",{"title":"Angular 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/angular/index.html"]],
  ["v-b3126996","/tag/es6/",{"title":"ES6 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/es6/index.html"]],
  ["v-3d184cee","/category/js/",{"title":"JS 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/js/index.html"]],
  ["v-5eb94b00","/tag/reactcli/",{"title":"ReactCli 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/reactcli/index.html"]],
  ["v-884bc6b0","/category/react/",{"title":"React 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/react/index.html"]],
  ["v-22f105a7","/tag/reactextends/",{"title":"ReactExtends 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/reactextends/index.html"]],
  ["v-65f6d381","/category/vue/",{"title":"Vue 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vue/index.html"]],
  ["v-2953c4b5","/tag/vue2/",{"title":"Vue2 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vue2/index.html"]],
  ["v-2953c4d4","/tag/vue3/",{"title":"Vue3 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vue3/index.html"]],
]
